### ISSUE TITLE
Image tracking documentation

### ISSUE THREAD

**Issue by SteveRavalisse** [EddyVerbruggen/nativescript-ar#100]
Hello, 
Would it be possible to have a full tutorial the image tracking?
I looked on the available readme and docs but I still couldn't manage to make it work.

Thanks

**Comment by EddyVerbruggen** [comment]
Docs: https://github.com/EddyVerbruggen/nativescript-ar/blob/master/docs/tracking-images.md

Demo: https://github.com/EddyVerbruggen/nativescript-ar/tree/master/demo-pokemon

Not sure what more I can do.
