### ISSUE TITLE
Animated Models ?

### ISSUE THREAD

**Issue by Universi** [EddyVerbruggen/nativescript-ar#11]
Hi @EddyVerbruggen,

Thank you for this awesome plugin !

Is it already possible to display animated models with it?

Thanks

**Comment by EddyVerbruggen** [comment]
Hi @Universi,

Can you perhaps share a (link to) animated model for me to test this with?

Cheers,
Eddy

**Comment by Universi** [comment]
Hi @EddyVerbruggen,

Here is one with .dae format : https://drive.google.com/open?id=1kA92r5tiYWhqpdmo7JLzi-eA5ozacUAZ

Best regards,

**Comment by sylwesterdigital** [comment]
I let myself to load that animated model and it works! https://youtu.be/XjAAi_lyhQI

**Comment by EddyVerbruggen** [comment]
@sylwesterdigital Haha that's so cute :)

I was searching for an animated model again today for a demo and found a spider. But I might just use that little dude instead. 👍

**Comment by EddyVerbruggen** [comment]
Works like a boss. Added it to the solarsystem demo. Also converted it to Android's glb format, but it looses the animation. May be fixed when using gltf insead but currently there's a bug in ARCore preventing me to use the converted model.

If you want to try the solarsystem demo, clone the repo and run `npm run demo.solarsystem.ios` from the `src` folder. The animated models have been added to Jupiter.
