### ISSUE TITLE
Get coordinates when object tapped 

### ISSUE THREAD

**Issue by adam-ali** [EddyVerbruggen/nativescript-ar#12]
Hi Eddy 

Is it possible to get the coordinates of where an object was Tapped or longPressed ? 

Thanks

**Comment by EddyVerbruggen** [comment]
You mean it works for boxes added to planes, but not for other geometry/models? If that's the case then indeed, there seems to be an issue with those events not firing.

**Comment by adam-ali** [comment]
well for me the onTap event didn't fire for boxes too, the longPressed event did work for me however it was only when i added a childNodeName to the model without this the longPressed didnt work too

**Comment by EddyVerbruggen** [comment]
Interesting observation on the longpress. I'll look into that.

Note that the tap events will work just fine with 0.5.0.

**Comment by adam-ali** [comment]
what I also wanted to ask was if is it possible to get the exact coordinates of the objects where it was tapped so I can use these coordinates to create a new object

**Comment by EddyVerbruggen** [comment]
Sorry, I didn't answer that indeed. At the moment you'll get the object back, but I can also probably send the tap coordinates. That would break the API a bit so I'll have to think about it a little. Reopening.

**Comment by EddyVerbruggen** [comment]
With 0.5.0 you'll get the x and y screen coordinates in the `onTap` and `onLongPress` callbacks. Demo and docs have been updated accordingly.
