### ISSUE TITLE
The plugin doesn't Work on ios 12.1.2

### ISSUE THREAD

**Issue by ebellumat** [EddyVerbruggen/nativescript-ar#20]
Following this tutorial for Angular, i got this I'm using iOS 12.1.2.

[Getting Started with Augmented Reality in NativeScript
](https://www.nativescript.org/blog/getting-started-with-augmented-reality-in-nativescript)

`file:///app/tns_modules/nativescript-ar/ar.js:164:24: JS ERROR TypeError: undefined is not an object (evaluating 'this.nativeView.addSubview')`

`*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'this.nativeView.addSubview') `

- [THE LOG](https://pastebin.com/HraFCy3U)

**Comment by EddyVerbruggen** [comment]
Without looking at the code (yet) it’s probably because of a change in NativeScript 5, and the tutorial (and plugin demo) are NativeScript 4. Should be an easy fix in the plugin though.

**Comment by ebellumat** [comment]
Its possible to do a downgrade my nativeScript version to test? =)

**Comment by EddyVerbruggen** [comment]
Indeed NativeScript 5 was the issue. The plugin is now compatibile with 5. Available on npm now (0.6.2).

**Comment by ebellumat** [comment]
Thanks @EddyVerbruggen .
