### ISSUE TITLE
JavaScript Error (evaluating 'faceGeometry.firstMaterial')

### ISSUE THREAD

**Issue by sebirkli** [EddyVerbruggen/nativescript-ar#27]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
I have installed the npm version 0.7.1 and followed https://github.com/EddyVerbruggen/nativescript-ar/blob/master/docs/ar-angular.md

I can install and start and for some seconds all works fine till I get this error:

***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x101397370 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1013c7dec NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x101e2c494 ffi_closure_SYSV_inner
4   0x101e301b4 .Ldo_closure
5   0x22d94beac <redacted>
6   0x22d9495c4 <redacted>
7   0x2256d6d9c <redacted>
8   0x2256d98b8 <redacted>
9   0x2256d9f24 <redacted>
10  0x2256da368 <redacted>
11  0x22578afa0 <redacted>
12  0x225622ca0 <redacted>
13  0x22574cc58 <redacted>
14  0x210c56484 <redacted>
15  0x210c035c8 <redacted>
16  0x22574cbc8 <redacted>
17  0x2156ea49c <redacted>
18  0x21147db24 IODispatchCalloutFromCFMessage
19  0x211186f0c <redacted>
20  0x2111ae758 <redacted>
21  0x2111adea4 <redacted>
22  0x2111a8c5c <redacted>
23  0x2111a80e0 CFRunLoopRunSpecific
24  0x211b9e494 <redacted>
25  0x225623044 <redacted>
26  0x225623178 <redacted>
27  0x210e3825c <redacted>
28  0x210e381bc _pthread_start
29  0x210e3bcf4 thread_start
JavaScript stack trace:
1   rendererNodeForAnchor@file:///app/tns_modules/nativescript-ar/ar.js:635:25
2   UIApplicationMain@[native code]
3   start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
4   run@file:///app/tns_modules/tns-core-modules/application/application.js:303:10
5   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:188:26
6   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:106:38
7   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:90:26
8   anonymous@file:///app/main.js:6:57
9   evaluate@[native code]
10  moduleEvaluation@[native code]
11  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-ar/ar.js:635:25: JS ERROR TypeError: null is not an object (evaluating 'faceGeometry.firstMaterial')

If I set detectPlanes="false" the app is able to run a little bit longer but still gets this error. I suppose this have to do something with  faceGeometry but wondering why. I'm not using it and also tried to set trackingMode="WORLD" but still getting this problem.

### Which platform(s) does your issue occur on?
iOS (only trying on iOS)

### Please, provide the following version numbers that your issue occurs with:
tns version: 5.2.4

**Comment by EddyVerbruggen** [comment]
That doesn't sound good. Let me take a look!

**Comment by sebirkli** [comment]
If I try the version 0.6.2. (https://github.com/EddyVerbruggen/nativescript-ar/issues/20) it works fine.

**Comment by EddyVerbruggen** [comment]
@sebirkli Sure, because the 'face' stuff was added in 0.7.0. Can you share the exact XML/HTML markup you're using to trigger this? I can't break it yet.

**Comment by sebirkli** [comment]
`<ActionBar title="NativeScript AR"></ActionBar>
<GridLayout rows="auto, *" class="page">
  <Label row="0"></Label>
  <AR
    row="1"
    debugLevel="FEATURE_POINTS"
    trackingMode="WORLD"
    detectPlanes="true"
    showStatistics="true"
    [planeMaterial]="planeMaterial"
    (planeTapped)="planeTapped($event)">
    
  </AR>
</GridLayout>`

**Comment by sebirkli** [comment]
`import { Component, OnInit } from '@angular/core';
import { AR, ARMaterial, ARPlaneTappedEventData } from "nativescript-ar";
import { Color } from "tns-core-modules/color";

import { registerElement } from "nativescript-angular/element-registry";
registerElement("AR", () => require("nativescript-ar").AR);

@Component({
  selector: 'ns-ar',
  templateUrl: './ar.component.html',
  styleUrls: ['./ar.component.css'],
  moduleId: module.id,
})
export class ArComponent implements OnInit {

  public planeMaterial = "Assets.scnassets/Materials/tron/tron-diffuse.png";

  constructor() {
    console.log("AR supported? " + AR.isSupported());
  }

  planeTapped(args: ARPlaneTappedEventData): void {
    console.log(`Plane tapped at ${args.position.x} y ${args.position.y} z ${args.position.z}`);
    const ar: AR = args.object;
    // interact with the 'ar' object here if you like
  }

  ngOnInit() {
  }

}`

**Comment by EddyVerbruggen** [comment]
And which device are you running on? Perhaps it's because iPhone X (my test device) has the 'true depth' camera for face tracking, and yours doesn't.

**Comment by sebirkli** [comment]
iPhone 7

**Comment by sebirkli** [comment]
Hm but why it uses this functionality if I didnt set it? I thought it will be used only if "FACE" is set for trackingMode.

**Comment by EddyVerbruggen** [comment]
That's why I've flagged this as a bug.

**Comment by EddyVerbruggen** [comment]
0.7.2 is now on npm.

**Comment by sebirkli** [comment]
@EddyVerbruggen Thx for that very fast fix. I will have a try later.
