### ISSUE TITLE
Add 📹videorecorder, so you can easily share your awesome AR experience

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-ar#31]
Got most of the code for this by email from @Emanuele-Fortunati 💙

**Comment by Emanuele-Fortunati** [comment]
@EddyVerbruggen My pleasure :) Cannot wait to see the code merged in!

**Comment by EddyVerbruggen** [comment]
Version 0.8.1 is now available on npm!

I've changed the API a little, so make sure to check [this example for playing a video](https://github.com/EddyVerbruggen/nativescript-ar/blob/a9a0b9e4abcf2f66f16f584eaa754a16fc219d65/demo/app/main-page.ts#L240-L250), and [this example](https://github.com/EddyVerbruggen/nativescript-ar/blob/934cf20958226561dbb8a52deba6074da3f9e451/demo/app/main-view-model.ts#L84-L100) or [the docs](https://github.com/EddyVerbruggen/nativescript-ar/blob/ba63bc6abbe3307a7cfbb80f0f93019a7b1b40aa/docs/api.md#startrecordingvideo--stoprecordingvideo-ios) for recording a video.
