### ISSUE TITLE
`Can't find variable: RecordAR` following tutorial

### ISSUE THREAD

**Issue by aaweb** [EddyVerbruggen/nativescript-ar#33]
Following the tutorial on https://www.nativescript.org/blog/getting-started-with-augmented-reality-in-nativescript, I get stuck after running `tns plugin add nativescript-ar` and editing `app/home/home.component.ts`.

I am getting the following error:
```
24  anonymous@file:///app/starter.js:<\M-b\M^@\M-&>
JavaScript error:
file:///app/vendor.js:80409:38: JS ERROR ReferenceError: Can't find variable: RecordAR
```

- tns version: 5.4.2
- tns-core-modules@~5.4.0

Any help much appreciated!

**Comment by EddyVerbruggen** [comment]
I guess that’s a native class added in a recent update. 

Does it help to remove your platforms/ios folder and build again?

**Comment by aaweb** [comment]
Thanks for your reply, Eddy (big fan of your work btw).

I tried removing platforms/ios and rerunning `tns run ios`, but same result.

I tried to start over from scratch as well and getting this error now. Not quite sure which one comes first:
```
Platform ios successfully added. v5.4.2
Preparing project...
Installing pods...
Analyzing dependencies
Pre-downloading: `ARVideoKit` from `https://github.com/EddyVerbruggen/ARVideoKit.git`, branch `swift_4_2`
[!] Unable to find a specification for 'ARVideoKit'.

[!] Unable to load a podspec from `ARVideoKit.podspec`, skipping:

Pod::DSLError
Unable to apply changes on device: 00008027-001A310221E3002E. Error is: 'pod install' command failed..
```

**Comment by EddyVerbruggen** [comment]
Did you try running `pod repo update`?

**Comment by aaweb** [comment]
That did the trick. Thanks a lot!
