### ISSUE TITLE
Add to Startup Doc

### ISSUE THREAD

**Issue by MentalGear** [EddyVerbruggen/nativescript-ar#35]
You might want to link this article to the docs, as it is great for beginners:
https://market.nativescript.org/plugins/nativescript-ar

**Comment by EddyVerbruggen** [comment]
That's literally [the README.md](https://github.com/EddyVerbruggen/nativescript-ar#nativescript-augmented-reality) in this repo 😉

**Comment by MentalGear** [comment]
Sorry dude, I meant to link to this article from TJ:
https://www.nativescript.org/blog/getting-started-with-augmented-reality-in-nativescript

**Comment by EddyVerbruggen** [comment]
Lol, I'll add it to the readme, thx!

**Comment by MentalGear** [comment]
Thx for your quick reply and the work on this, Eddy !
