### ISSUE TITLE
Vuejs support

### ISSUE THREAD

**Issue by sylwesterdigital** [EddyVerbruggen/nativescript-ar#36]
I tried to run demo app but seems to me not compatible with the latest CLI and Webpack. 
I tried migration first: 
```$ tns migrate``` and then ```$ tns run ios```
but failed
```
Unknown argument: preserve-symlinks
```
Can you update your repo for VueJS? Ta

**Comment by EddyVerbruggen** [comment]
I'll add a Vue demo, but I've also migrated the TS demo in this repo to NativeScript 6. So maybe that helps.
