### ISSUE TITLE
Capture camera stream

### ISSUE THREAD

**Issue by maxkuzmin** [EddyVerbruggen/nativescript-ar#5]
Hello. We build app like snapchart: we have to capture camera stream, recognize some objects and place virtual objects to particular screen coordinates. We already have code that recognizes objects. Can we capture camera stream using this package now or in the future? Thanks in advance.

**Comment by geoffbullen** [comment]
@maxkuzmin did you figure out how to get the camera stream?

**Comment by maxkuzmin** [comment]
@geoffbullen it seems there is not easy way to solve it using native script. I decided to use React Native.

**Comment by EddyVerbruggen** [comment]
@geoffbullen I'm not entirey sure what you're after. With requests like these, it's very helpful if you could Google how to do this in a native iOS project with ARKit. Perhaps there's a demo somewhere of what you want to achieve, or (even better) some sample code that I can take a look at.

**Comment by geoffbullen** [comment]
Thanks @EddyVerbruggen.   Right now, I have some opencv based object detection code.   I'd like to write a nativescript app (supporting android too eventually) that processes the camera video, uses opencv to detect stuff, and then overlays an AR experience.

And, I came across this - https://medium.com/@BienThere/combining-arkit-and-opencv-5c010b268a45 and was exploring whether this would help me...

**Comment by EddyVerbruggen** [comment]
With ARKit there's an option to grab a screenshot. I haven't seen a function to grab the camera stream, but for detecting stuff in images it may be sufficient so I'm going to implement that for now.
