### ISSUE TITLE
Add an ImageTracking demo, in NativeScript-Angular

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-ar#62]
Try to replicate the [Android Augmented Image demo](https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/augmentedimage) for iOS and Android in NativeScript.

And we need an Angular demo as well, so that seems like a good opportunity.

It would be cool to replicate something like this: https://www.youtube.com/watch?v=ZhHExAxyVow

**Comment by zenslainer** [comment]
Do you have an estimation of delay for  getting the arCore AugmentedImage to be integrated?

**Comment by EddyVerbruggen** [comment]
When. It's. Done.

**Comment by nickolanack** [comment]
@EddyVerbruggen Have you gotten Image tracking working for IOS?

**Comment by EddyVerbruggen** [comment]
@nickolanack Yeah, that's part of the plugin for a while now actually. If you want to try it, do what  [this line](https://github.com/EddyVerbruggen/nativescript-ar/blob/7e4380ebb4254a25ca6d5a091fa2c31f2eb17ebc/demo/app/main-page.xml#L20) says and run the demo app.

So change the value of `trackingMode` to `IMAGE` and check out the images mentioned. You could simply load one of those images on your computer screen, then point your app at the screen and it should work.

**Comment by EddyVerbruggen** [comment]
Btw, I'm not religious about this demo needing to be in Angular, as long as it demonstrates the feature. Although I occasionally get asked how to use AR (or any other plugin for that matter) with Angular.

**Comment by nickolanack** [comment]
I think it is a good idea to have an Angular demo - (I'm not particularly competent using vue, angular, or typescript tbh) but happy to contribute anyway.

**Comment by EddyVerbruggen** [comment]
Cool! With the NativeScript CLI is really easy to create one. Just run `tns create demo-ng` in the plugin project root and follow the steps.

We need a few commands in `src/package.json` afterwards, but I've done that a million times already so don't sweat it.

**Comment by nickolanack** [comment]
is it possibility to track world and images at the same time?

**Comment by EddyVerbruggen** [comment]
AFAIK not, but I haven't tried/investigated it either. It depends on what can be set [here](https://github.com/EddyVerbruggen/nativescript-ar/blob/7e4380ebb4254a25ca6d5a091fa2c31f2eb17ebc/src/ar.ios.ts#L213), and I always assumed it was one of "world", "face", or "image" (look at where `this.configuration` is set).

**Comment by nickolanack** [comment]
https://developer.apple.com/documentation/arkit/arimagetrackingconfiguration?language=objc
` ARWorldTrackingConfiguration can also detect images, but each configuration has its own strengths:`
looks like image tracking can work in 'world' mode... but is less performant

**Comment by nickolanack** [comment]
#63 added a basic image tracking implementation for android

**Comment by EddyVerbruggen** [comment]
I'll add a basic demo today. I've got a cool idea for this image tracking demo.

**Comment by nickolanack** [comment]
Cool!, I’ll update android to add all images in trackingImagesBundle and PR today as well

**Comment by EddyVerbruggen** [comment]
Awesome! Btw, I was looking for a tool to transform Collada models (.dae, for iOS) into and Android-compatible format and found one that seems to do the job well. I’ll add details to the readme after some more testing.

**Comment by EddyVerbruggen** [comment]
Update: this will take me another day or 2 to complete. Shaping up pretty well and fixing a few issues (on iOS currently) in the process.

**Comment by nickolanack** [comment]
Cool, excited to see

**Comment by EddyVerbruggen** [comment]
Holy 🐄that was quite some tweakin'.

@nickolanack Whenever you have time I'd love you to check out the new Angular Pokémon image tracking demo. Make sure to __check iOS first__ as that's how it's intended to work.

Once installed via `npm run demo.pokemon.ios` you can open the menu and access two routes with AR features:

- __"Augment Card"__: Scan [this image](https://raw.githubusercontent.com/EddyVerbruggen/nativescript-ar/master/demo-pokemon/App_Resources/Android/src/main/assets/PokemonResources/Eevee.jpg) and it should play a video, add a model, and an image (of a "star"). Upon tapping the star it changes to a different image and another image (of a Pokemon) added on top of that. It will also change application state by marking the Pokemon as a favorite and [storing the setting](https://github.com/EddyVerbruggen/nativescript-ar/blob/6a8a44faf1a1c28941cb4ea6c06eb46f07641e20/demo-pokemon/src/app/pokemon-data/pokemon-favorites-service.ts#L19) in "local storage" so it persists between app launches. Oh, and by tapping the model it will start rotating. Tapping it again makes it stop.
- __"Search By Card"__: This is the list of all Pokemon the app cares about. The idea is you can find your favorite Pokemon by scrolling through the list, and tapping it for details (not much to see there yet). You'll also see whether or not you've marked it as favorite and you can do so by tapping the star here as well. When pressing the image in the top right you can scan a Pokemon card and it will take you to the details. This way you don't use AR to really augment anything, but rather to recognize an object and quickly get back into your flow of work.

### Android issues
The Android UI has a few glitches I didn't have time to fix yet, but once you've seen the iOS UI you'll see where it's going.

The two biggest issues I see are:
- Loading the images (especially larger ones) take some time, which freezes the UI. But worse: once the camera is loaded nothing is recognized until you load the camera a second time.
- Images and models placed on top of recognized images are incorrectly rotated; I think we have to rotate the x-axis `-90` degrees to fix it (but I'm not sure where) because currently setting fi the y-position affects the z-position. This can be clearly observed by increasing the value [on this line](https://github.com/EddyVerbruggen/nativescript-ar/blob/6a8a44faf1a1c28941cb4ea6c06eb46f07641e20/demo-pokemon/src/app/browse/browse.component.ts#L54) from `0.1` to `0.5` (it moves towards the camera).

**Comment by nickolanack** [comment]
Cool I’ll check this out shortly

**Comment by nickolanack** [comment]
That’s freaking cool! Good work

**Comment by nickolanack** [comment]
I think we just need to add a node between the image tracking anchor and user nodes that corrects the orientation/scale to match iOS - I’ll play around with it!

**Comment by EddyVerbruggen** [comment]
Thanks mate! I read about that approach (adding a node in between) somewhere but didn’t try it yet. It makes sense and I hope you’re able to pull it off 😋

**Comment by EddyVerbruggen** [comment]
Bar some differences in how scaling works I think we can close this now. Thanks!
