### ISSUE TITLE
Android support now that ARCore 1.0 is released

### ISSUE THREAD

**Issue by krisidmisso** [EddyVerbruggen/nativescript-ar#8]
Its more a question than a issue. The ARCore 1.0 is out and they added support down to samsung s7( https://www.blog.google/products/google-vr/announcing-arcore-10-and-new-updates-google-lens/ ). Is there going to be a android support for this plugin soon? I really love AR. Thank you

**Comment by EddyVerbruggen** [comment]
Yes, I have a local version with ARCore 1.0 working, but it doesn't support a lot of features yet. I hope to be able to find some time to work on this plugin in the near future.

**Comment by peterugah** [comment]
Please, I really look forward to ARCore support for nativescript.
