### ISSUE TITLE
Get current device position

### ISSUE THREAD

**Issue by Felix212** [EddyVerbruggen/nativescript-ar#81]
Hello i am trying get the current device position, but I can not find anything about it in the docs. 
I want to calculate the distance between a node and my device.

**Comment by EddyVerbruggen** [comment]
@Felix212 Good question!

It's actually not properly exposed by the plugin but it is there. Please check [this demo code](https://github.com/EddyVerbruggen/nativescript-ar/blob/7d1d013fb895fe97b4ac7197e21726bf25c2ee50/demo-solarsystem/app/components/App.vue#L376).

I'll add it to the API.
