### ISSUE TITLE
Add a "getPositionOnScreen" function to map 3D AR World objects to x/y screen coordinates

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-ar#83]
It would be helpful to fi. programmatically know if an object is in a certain place (x/y) on the screen. So fi. when a sphere/model is in or near the center of the screen we can consider the user looking at it.

**Comment by EddyVerbruggen** [comment]
[Here's a nice demo](https://github.com/EddyVerbruggen/nativescript-ar/blob/69b5bf24903717efc5f3611b2e6f2974f6d97973/demo-solarsystem/app/components/App.vue#L454) of how this can be used.

**Comment by nickolanack** [comment]
just out of curiosity, what happens if an object is directly behind you (and the camera)? 
-- with apologies since i could check myself...

**Comment by nickolanack** [comment]
Ok, I checked... items directly behind you also have onscreen x, y coordinates  (which is what I thought would happen).

**Comment by EddyVerbruggen** [comment]
You're right. That makes it a bit harder to do what I wanted to achieve, but I've found a satisfactory way around it. Will test on Android tomorrow a little and update the repo.

**Comment by nickolanack** [comment]
Btw - There is a Dot product rule to test if an object is in front or behind

**Comment by nickolanack** [comment]
Dot product of: direction vector (camera to object), and camera look direction vector

**Comment by nickolanack** [comment]
It would also be cool (feature) if there was a way to expose hit testing/raytracing

**Comment by EddyVerbruggen** [comment]
That sounds like a much better approach, but I need this feature for a presentation I'm doing soon so I'll stick to the half-baked solution I have now. Sounds like a great plan though, to add a `node.isInFrontOfCamera()` function to the plugin. Or maybe even something like `node.getPositionRelativeToCamera()`.
