### ISSUE TITLE
DataUnsupportedVersionException on recognition start

### ISSUE THREAD

**Issue by alshap** [EddyVerbruggen/nativescript-ar#99]
Hello,

Got this error on image recognition starting

`
JS: Error: com.google.ar.core.exceptions.DataUnsupportedVersionException
JS:     java.lang.reflect.Constructor.newInstance0(Native Method)
JS:     java.lang.reflect.Constructor.newInstance(Constructor.java:334)
JS:     com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:145)
JS:     com.google.ar.core.AugmentedImageDatabase.nativeDeserialize(Native Method)
JS:     com.google.ar.core.AugmentedImageDatabase.deserialize(AugmentedImageDatabase.java:2)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1083)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1063)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1055)
JS:     com.tns.NativeScriptActivity.onPostResume(NativeScriptActivity.java:24)
JS:     android.app.Activity.performResume(Activity.java:7385)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
JS:     android.app.ActivityThread.hand...
`
Code looks fine and all was created like in demo-pokemon.
Any ideas?

**Comment by EddyVerbruggen** [comment]
Did you Google that error? It looks like something from ARCore.

**Comment by alshap** [comment]
Yes, but found only 
```
public class DataUnsupportedVersionException
The data passed in for this operation is not supported by this version of the SDK.
```
Have no idea from where exception come. Think that it does not see my android images bundle
